name: Laravel CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  laravel-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, sqlite3, xml, bcmath
          tools: composer

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install npm dependencies
        run: npm install

      - name: Build frontend assets
        run: npm run build

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Run Laravel Pint
        run: ./vendor/bin/pint

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run migrations
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan migrate --env=testing

      - name: Execute tests via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test

      - name: Send Email Notification
        if: always()
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: smtp.gmail.com
          smtp-port: 465
          smtp-secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to-email: bjorntelkamp2000@gmail.com
          from-email: bjorntelkamp2000@gmail.com
          subject: Workflow ${{ github.workflow }} - ${{ job.status }}
          html: |
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <style>
                    body {
                        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
                        margin: 0;
                        padding: 0;
                        background-color: #000000;
                        color: #f5f5f5 !important;
                    }

                    .container {
                        max-width: 600px;
                        margin: 20px auto;
                        background-color: #1a1a1a;
                        border-radius: 8px;
                        padding: 20px;
                    }

                    .header {
                        text-align: center;
                        padding-bottom: 20px;
                        border-bottom: 1px solid #333333;
                    }

                    .header img {
                        max-width: 150px;
                        height: auto;
                    }

                    .content {
                        padding: 20px;
                    }

                    .status {
                        font-size: 24px;
                        font-weight: bold;
                        text-align: center;
                        margin-bottom: 20px;
                    }

                    .success {
                        color: #2da44e;
                    }

                    .failure {
                        color: #cf222e;
                    }

                    .icon {
                        display: inline-block;
                        vertical-align: middle;
                        margin-right: 10px;
                    }

                    .details, .steps, .errors {
                        margin: 20px 0;
                    }

                    .details p, .steps p, .errors p {
                        margin: 10px 0;
                    }

                    .steps ul, .errors ul {
                        list-style-type: none;
                        padding-left: 0;
                    }

                    .steps li {
                        margin: 5px 0;
                    }

                    .errors {
                        color: #ff9999;
                    }

                    .button-container {
                        text-align: center;
                        margin: 20px 0;
                    }

                    .button {
                        display: inline-block;
                        padding: 12px 24px;
                        background-color: #007bff;
                        color: #f5f5f5;
                        text-decoration: none;
                        border-radius: 4px;
                        font-weight: bold;
                    }

                    .footer {
                        text-align: center;
                        padding-top: 10px;
                        font-size: 12px;
                        color: #999999;
                        border-top: 1px solid #333333;
                    }
                </style>
            </head>
            <body>
            <div class="container">
                <div class="header">
                    ${{ github.repository }}
                </div>
                <div class="content">
                    <div class="status ${{ job.status == 'success' && 'success' || 'failure' }}">
                                 <span class="icon">
                                   ${{ job.status == 'success' && '<svg width="28" height="28" viewBox="0 0 16 16"
                                                                        style="fill: #2da44e;"><circle cx="8" cy="8" r="8" /><path
                                     d="M8 16A8 8 0 1 1 8 0a8 8 0 0 1 0 16Zm3.78-9.72a.751.751 0 0 0-.018-1.042.751.751 0 0 0-1.042-.018L6.75 9.19 5.28 7.72a.751.751 0 0 0-1.042.018.751.751 0 0 0-.018 1.042l2 2a.75.75 0 0 0 1.06 0Z"
                                     fill="#ffffff" /></svg>' || '<svg width="28" height="28" viewBox="0 0 16 16"
                                                                       style="fill: #cf222e;"><circle cx="8" cy="8" r="8" /><path
                                     d="M2.343 13.657A8 8 0 1 1 13.658 2.343 8 8 0 0 1 2.343 13.657ZM6.03 4.97a.751.751 0 0 0-1.042.018.751.751 0 0 0-.018 1.042L6.94 8 4.97 9.97a.749.749 0 0 0 .326 1.275.749.749 0 0 0 .734-.215L8 9.06l1.97 1.97a.749.749 0 0 0 1.275-.326.749.749 0 0 0-.215-.734L9.06 8l1.97-1.97a.749.749 0 0 0-.326-1.275.749.749 0 0 0-.734.215L8 6.94Z"
                                     fill="#ffffff" /></svg>' }}
                                 </span>
                        ${{ job.status == 'success' && 'Success' || 'Failed' }}
                    </div>
                    <div class="details">
                        <p>The workflow run for <strong>${{ github.repository }}</strong> has completed.</p>
                        <p><strong>Branch:</strong> ${{ github.ref }}</p>
                        <p><strong>Commit:</strong> ${{ github.sha }}</p>
                        <p><strong>Repository:</strong> ${{ github.repository }}</p>
                    </div>
                    <div class="steps">
                        <p><strong>Steps Executed:</strong></p>
                        <ul>
                            <li ${{ steps.checkout.outcome==
                            'success' && '' || 'style="color: #ff9999"' }}>${{ steps.checkout.name }} - ${{ steps.checkout.outcome
                            }}</li>
                            <li ${{ steps.setup-php.outcome==
                            'success' && '' || 'style="color: #ff9999"' }}>${{ steps.setup-php.name }} - ${{ steps.setup-php.outcome
                            }}</li>
                            <li ${{ steps.composer-install.outcome==
                            'success' && '' || 'style="color: #ff9999"' }}>${{ steps.composer-install.name }} - ${{
                            steps.composer-install.outcome }}</li>
                            <li ${{ steps.pint.outcome==
                            'success' && '' || 'style="color: #ff9999"' }}>${{ steps.pint.name }} - ${{ steps.pint.outcome }}</li>
                            <li ${{ steps.tests.outcome==
                            'success' && '' || 'style="color: #ff9999"' }}>${{ steps.tests.name }} - ${{ steps.tests.outcome }}</li>
                        </ul>
                    </div>
                    ${{ job.status == 'failure' && '
                    <div class="errors">
                        <p><strong>Errors:</strong></p>
                        <ul>
                            <li>Workflow failed. See run logs at <a
                                href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                                style="color: #66b3ff;">${{ github.server_url }}/${{ github.repository }}/actions/runs/${{
                                github.run_id }}</a> for details.
                            </li>
                        </ul>
                    </div>
                    ' || '' }}
                    <div class="button-container">
                        <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                           class="button">View Run Details</a>
                    </div>
                </div>
                <div class="footer">
                    Sent from GitHub Actions | Made by Bjorn Telkamp
                </div>
            </div>
            </body>
            </html>
        continue-on-error: true

      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: laravel-logs
          path: storage/logs/*.log
        continue-on-error: true
