name: Laravel CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  laravel-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, sqlite3, xml, bcmath
          tools: composer

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install npm dependencies
        run: npm install

      - name: Build frontend assets
        run: npm run build

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Run Laravel Pint
        run: ./vendor/bin/pint

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run migrations
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan migrate --env=testing

      - name: Execute tests via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test

      - name: Send Email Notification
        if: always()
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: smtp.gmail.com
          smtp-port: 465
          smtp-secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to-email: bjorntelkamp2000@gmail.com
          from-email: bjorntelkamp2000@gmail.com
          subject: Workflow ${{ github.workflow }} - ${{ job.status }}
          html: |
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <style>
                    body {
                        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
                        margin: 0;
                        padding: 0;
                        background-color: #000000;
                    }

                    .container {
                        max-width: 600px;
                        margin: 20px auto;
                        background-color: #1a1a1a;
                        border-radius: 8px;
                        padding: 20px;
                        color: #f5f5f5;
                    }

                    .header {
                        text-align: center;
                        padding-bottom: 20px;
                        border-bottom: 1px solid #333333;
                        color: #f5f5f5;
                    }

                    .header img {
                        max-width: 150px;
                        height: auto;
                    }

                    .content {
                        padding: 20px;
                        color: #f5f5f5;
                    }

                    .status {
                        font-size: 24px;
                        font-weight: bold;
                        text-align: center;
                        margin-bottom: 20px;
                        color: ${{ job.status == 'success' && '#2da44e' || '#cf222e' }
                    }

                    ;
                    }
                    .icon {
                        display: inline-block;
                        vertical-align: middle;
                        margin-right: 10px;
                        width: 28px;
                        height: 28px;
                        border-radius: 50%;
                        background-color: ${{ job.status == 'success' && '#2da44e' || '#cf222e' }
                    }

                    ;
                    text-align: center

                    ;
                    line-height:

                    28
                    px

                    ;
                    }
                    .icon img {
                        width: 16px;
                        height: 16px;
                        vertical-align: middle;
                    }

                    .details {
                        margin: 20px 0;
                        color: #f5f5f5;
                    }

                    .details p {
                        margin: 10px 0;
                        color: #f5f5f5;
                    }

                    .button-container {
                        text-align: center;
                        margin: 20px 0;
                    }

                    .button {
                        display: inline-block;
                        padding: 12px 24px;
                        background-color: #007bff;
                        color: #f5f5f5;
                        text-decoration: none;
                        border-radius: 4px;
                        font-weight: bold;
                    }

                    .footer {
                        text-align: center;
                        padding-top: 10px;
                        font-size: 12px;
                        color: #999999;
                        border-top: 1px solid #333333;
                    }
                </style>
            </head>
            <body>
            <div class="container">
                <div class="header">
                    ${{ github.repository }}
                </div>
                <div class="content">
                    <div class="status">
                                        <span class="icon">
                                            ${{ job.status == 'success' && '<img
                                            src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAFFJREFUOE9jZKAQMILEmZmZ/zIwMjAw/2NgZJjDMB+EsQEToyQDy78nMDIwMhMhJCNsR0RERAwMjIxExA0MjAyMDEQMDIyMhM8QJCNsR0QkAAYA5poMNaC/H/YAAAAASUVORK5CYII="
                                            alt="Checkmark">' || '<img
                                            src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAGlJREFUOE9jZKAQMOG/gYGB4T8DA8P/GZhA8T8GEgYGBob/DIyMDEQMDIyM/5mRkZGZgYGBkYHhPwMjIyMRAwMjI/8zMDIyEjEwMDIy/2dgZGRiYGBgZGD4z8DIyEjEwMDIyP8MjIyMRAwA2poMNe8Q5bsAAAAASUVORK5CYII="
                                            alt="X">' }}
                                        </span>
                        ${{ job.status == 'success' && 'Success' || 'Failed' }}
                    </div>
                    <div class="details">
                        <p>The workflow run for <strong>${{ github.repository }}</strong> has completed.</p>
                        <p><strong>Branch:</strong> ${{ github.ref }}</p>
                        <p><strong>Commit:</strong> ${{ github.sha }}</p>
                        <p><strong>Repository:</strong> ${{ github.repository }}</p>
                    </div>
                    <div class="button-container">
                        <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                           class="button">View Run Details</a>
                    </div>
                </div>
                <div class="footer">
                    Sent from GitHub Actions | Made by Bjorn Telkamp
                </div>
            </div>
            </body>
            </html>
        continue-on-error: true

      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: laravel-logs
          path: storage/logs/*.log
        continue-on-error: true
